### ISSUE TITLE
レベル２:Javascriptで作成に挑戦

### ISSUE THREAD

**Issue by ro50s** [teamdev-C-2024-6/work-space#19]
一通り作成できたので、Javascriptで作成にも挑戦してみますか？

**Comment by sakuro468** [comment]
私はJavaScript部分を書くことが難しいと感じるので、ro50sさんかTakatoさんがJavaScriptを担当してくださるのであれば、レベル2に挑戦してみても良いかと思います。

**Comment by ro50s** [comment]
私もJavascriptでhtmlに書き込んだ経験はほとんどないので、苦戦すると思います。ただ、まだ6/30(日)まで3日あるので、触れてもいいかなと思っただけです。

やると決めたら、私は書きたいと思ってます。

追記
　終わったIssueはcloseしておきます。

**Comment by sakuro468** [comment]
了解しました。

もしかしたら、issuesだとTakatoさんに通知が届いていないかもしれないので、やっぱりDiscord上で連絡しあう方が良いのかもしれません。

**Comment by ro50s** [comment]
まだ2日あるので、Javascriptで作成に挑戦してみようと思います。

終わるか見当もつきませんが、しっかりと動いたら、6/30(日)20:00にプルリク送ります。

終わらなかったら、jsファイルはそのままでデプロイします。

**Comment by ro50s** [comment]
以下、考えられるタスク書いておきます。

### ・結果ページを作成
**・そのためにすること**

・おみくじオブジェクトに以下データを追加

- 　this.fortune = fortune;
- 　this.language = language;
- 　this.DB = DB;
- 　this.editor = editor;
- 　this.image = image;

　　
・getRandomNumber(max)によって、以下を取得。

- ラッキー言語、
- ラッキーデータベース、
- ラッキーエディタ
- 画像

・omikujiFrame.innerHTML = で書き込み

　・現おみくじページを再現
　㊟変数は${変数名}で書く

・omikujiBodyにomikujiFrameを追加

問題が見つかり次第、追加していきます。

**Comment by ro50s** [comment]
完成が難しいので、このままでデプロイします。もし何か修正を加えたくて、デプロイを遅らせてほしい場合は、コメントを残していただきたく思います。

**Comment by sakuro468** [comment]
お疲れ様です。
このままデプロイしていただいて構いません。
よろしくお願いいたします。
