### ISSUE TITLE
運勢のページ

### ISSUE THREAD

**Issue by ro50s** [teamdev-C-2024-6/work-space#9]

**Comment by ro50s** [comment]
暫定４つのページをHTMLで作成しましょう

**Comment by ro50s** [comment]
運勢のページは以下の要素を含むようにお願いします。

・御籤のタイトル
・画像
・説明
・ラッキー言語
・ラッキーデータベース
・ラッキーエディタ
・もう一度おみくじを引くボタン

以上７つをお願いします。

**Comment by ro50s** [comment]
HTMLのページの担当は以下のようになりました。

・Takatoさん：badLuck.html
・sakuroさん：lucky.html
・ro50s：goodFortune.html

**Comment by sakuro468** [comment]
lucky.htmlを一旦完成させました。

ro50sさん
私の環境下では、goodFortune.htmlの画像が表示できないみたいです。ro50sさんの環境下で表示されているか、ご確認いただけますか？

h1セレクタについては、index.htmlの雛形をTakatoさんが作成してくださった際のコードでしたので、これからindex.htmlを編集するのであれあば、削除しても影響はないと思い、私が削除しました。

**Comment by ro50s** [comment]
sakuroさん、lucky.htmlを作ってくださり、ありがとうございます。

私のPCでは、四葉のクローバーの画像が表示されています。ただ、他環境上で表示されない場合を考慮して、いらすとやからそれっぽい画像を入れておきます。

h1タグをsakuroさんが消していたことに気づきませんでした。確認不足で申し訳ございません。

確かに、index.htmlはこれから完成させていくため、h1タグは現段階ではなくてもよさそうですね。

必要な時に、h1セレクタに要素を追加していったほうが良さそうです。
